fix: update the schema of bridgeTransactionID's signature
CoolBitX-Technology/sygna-bridge-developers-doc pull request #17
Opened 2020-10-12 10:10 UTC by pin850406

2020-10-12 10:16 UTC, kunmingLiu commented on bridge-api.json
> +            "type": "string",
- 應該用ref的方式比較好，這樣以後改的話，不用改多個地方

- 相同物件中的transfer_id可能也加一下檢查，可以參考bridgeTransferData.transfer_id

2020-10-12 10:16 UTC, kunmingLiu requested changes
使用ref的方式可能比較好

2020-10-13 10:23 UTC, kunmingLiu commented on bridge-api.json
> +                    "$ref": "#/components/schemas/bridgeVaspData/properties/vasp_code"
因為現在有很多地方都會參考到vasp_code，或許把vasp_code獨立成一個定義(ie. bridgeTransferID)，然後每個有需要vasp_code的地方都去參考這個定義，也許會比去參考某個定義下的properties會稍微好讀跟好維護一點

2020-10-13 10:24 UTC, kunmingLiu requested changes
也許將vasp_code獨立出去會好看一點

2020-10-15 07:18 UTC, kunmingLiu approved these changes
LGTM

2020-10-15 07:22 UTC, s60912frank approved these changes

2020-10-15 07:32 UTC, merged