feat: add a new API-KYT
CoolBitX-Technology/sygna-bridge-developers-doc pull request #30
Opened 2020-12-28 04:06 UTC by pin850406

2020-12-29 02:26 UTC, kunmingLiu commented on bridge-api.json
> +            "type":"integer"
example的usd_worth都是給小數，但是這邊卻是給整數

2020-12-29 02:30 UTC, kunmingLiu commented on bridge-api.json
> +            "$ref": "#/components/schemas/bridgeAddress"
bridgeAddress是個{address:string,addr_extra_info:{}[]}，請確認kyt的addrs是單純的字串陣列還是它可以接受addr_extra_info

2020-12-29 02:35 UTC, kunmingLiu commented on bridge-api.json
> +        "description": "Know-Your-Customer",
此處desccription需要再討論

2020-12-29 02:37 UTC, kunmingLiu approved these changes
請再幫忙確認，謝謝

2020-12-29 02:37 UTC, kunmingLiu requested changes
請再幫忙確認，謝謝

2020-12-29 02:51 UTC, pin850406 commented on bridge-api.json
> +        "description": "Know-Your-Customer",
KYT的description的部分,Vince說周三下午會再給我
這邊我先留空白好了
謝謝

2020-12-29 03:26 UTC, kunmingLiu commented on bridge-api.json
> +        "description": "Know-Your-Customer",
既然會再改可以先不變，我只是先留個紀錄而已，提醒說這邊記得要改

2020-12-29 06:05 UTC, pin850406 commented on bridge-api.json
> +        "description": "Know-Your-Customer",
好的 感謝！

2020-12-29 07:21 UTC, kunmingLiu commented on bridge-api.json
> +            "type":"integer"
根據Ellitpic的網站來看，risk_score可能會是小數
<img width="580" alt="截圖 2020-12-29 15 20 57" src="https://user-images.githubusercontent.com/14188660/103265867-8f944a80-49e9-11eb-9447-196266d71d83.png">

2020-12-29 07:22 UTC, kunmingLiu requested changes
請幫忙修改，謝謝

2020-12-29 07:24 UTC, pin850406 commented on bridge-api.json
> +            "type":"integer"
好的 謝謝

2020-12-30 02:21 UTC, kunmingLiu approved these changes
LGTM

2020-12-31 02:34 UTC, s60912frank approved these changes

2020-12-31 02:35 UTC, merged